### ISSUE TITLE
Problem with +tag in the title when using fetching from a mailbox

### ISSUE THREAD

**Issue by bepolymathe** [joplin/plugin-email#10]
Hi @bishoy-magdy 

After some tests (and unless I'm mistaken), it seems that tags are not correctly supported in the title when using the option to retrieve all new messages from a mailbox rather than from a particular address.

**Comment by bishoy-magdy** [comment]
Hi @bepolymathe 

A big thanks for testing the plugin.

Honestly, this isn't an issue. I've already prevented the use of @ or # in the subject or first line in mailbox monitoring, which means it adds folders or tags by using the @ or # syntax when only monitoring a specific email account (**You can only, in this case, edit the subject or first line of an email**). This is because the mailbox monitoring feature is for users who don't want to use forwarding or monitor a specific e-mail, so it just fetches new or unread messages from the specified mailbox and puts them in the folder that the user-specified.

**Comment by bepolymathe** [comment]
I understand your point of view. Let me explain my use case. I have two main emails. One professional, one personal. I have a third address to which I forward the pro or personal emails that need it. For example, I would like to transfer pro mail by passing the "pro" tag.
I would find it useful... but I can live without it.

**Comment by bishoy-magdy** [comment]
This sounds like a great idea, I will mark it as a feature, but this feature will only work when monitoring only the inbox because that's the only place where the new message will be!

Do you think +folder support in the subject while mailbox monitoring is also useful if the user wants to map the note to more than one folder?

**Comment by bepolymathe** [comment]
> I will mark it as a feature

Oh great ! 



> but this feature will only work when monitoring only the inbox because that's the only place where the new message will be

That’s fine ! 



> Do you think +folder support in the subject while mailbox monitoring is also useful if the user wants to map the note to more than one folder?

I'm not sure that's necessary...
